name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - run: corepack enable
      - run: yarn install --frozen-lockfile
      - name: Check
        run: yarn format:diff
